### PR TITLE
Added points for https://github.com/keploy/keploy/issues/2095 to leaderboard (yaten2302)

### PR DESCRIPTION
**Pull request by yaten2302**
Updated leaderboard for this issue(level-1) - https://github.com/keploy/keploy/issues/2095

### CODE REVIEW

**Review by Swpn0neel — CHANGES_REQUESTED** [review]
resolve conflicts!

**Comment by yaten2302** [comment]
@Swpn0neel sir, could you please check that now are the conflicts resolved?

**Review by Swpn0neel — CHANGES_REQUESTED** [review]
Why have you removed Debayan's entry?

**Comment by yaten2302** [comment]
@Swpn0neel sir, sorry for that, I by mistake removed someone's entry. Now, could you please check that is it working fine?

**Review by Swpn0neel — CHANGES_REQUESTED** [review]
There are multiple instances of participants in your PR... If you're getting confused, you can make a new PR!!

**Comment by yaten2302** [comment]
Sure, I'll create a new PR for this 👍

**Pull request closed without merging**
