### PR TITLE
Fixed the "Explore More" links in keploy.io

### PR DESCRIPTION
**Pull request by yaten2302**
Fixed issue - [#2074](https://github.com/keploy/keploy/issues/2074) under `kROC` label.

### CODE REVIEW

**Review by Swpn0neel — CHANGES_REQUESTED** [review]
Can you fix the DCO check? Take reference from here: https://github.com/keploy/.github/pull/16/checks

**Comment by yaten2302** [comment]
@Swpn0neel sir, should I again make some changes in this repo and then run `git commit -s -m ""` ?

**Comment by Swpn0neel** [comment]
No, see from the link I've provided... you just need to rebase it! And moving forward, please don't forget to sign your commits!

**Comment by yaten2302** [comment]
@Swpn0neel sir, I've now pushed the changes, could you please check <br>
image

**Comment by yaten2302** [comment]
@Swpn0neel sir, when I'm checking out the PR, some changes are being made automatically, could you please guide <br>
image

**Comment by Swpn0neel** [comment]
I think you had some previous unstaged changes that's causing the issue

**Comment by yaten2302** [comment]
Sorry @Swpn0neel sir, I was doing that in some other repo. Now, I've done it 👍 could you please check.

**Pull request merged**
