### PR TITLE
Updating leaderboard

### PR DESCRIPTION
**Pull request by shreyashrpawar**
Issue solved by PR [#10](https://github.com/keploy/writers-program/pull/10)

### CODE REVIEW

**Review by Swpn0neel — APPROVED** [review]
I'll merge it once the main PR gets merged!

**Comment by shreyashrpawar** [comment]
Okay Thanks

**Comment by Swpn0neel** [comment]
Please resolve the conflicts, then I can merge it!

**Comment by shreyashrpawar** [comment]
Resolved the Conflict. Please merge the request.

**Review by Swpn0neel — APPROVED** [review]

**Pull request merged**
