### PR TITLE
Added point for issue 2106

### PR DESCRIPTION
**Pull request by ayush3160**
Added points for issue [2106](https://github.com/keploy/keploy/issues/2106) and for PR [427](https://github.com/keploy/docs/pull/427)

### CODE REVIEW

**Comment by Swpn0neel** [comment]
resolve conflicts!

**Comment by ayush3160** [comment]
@Swpn0neel , I have made the changes and have added some new points. I have added entry for issue2140 but don't know about the points of it , Let me know if it has any points. I'll do the changes.
Thanks.

**Comment by Swpn0neel** [comment]
3 points!

**Comment by ayush3160** [comment]
@Swpn0neel , Done please have a look

**Review by Swpn0neel — APPROVED** [review]

**Pull request merged**
